apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: app-config  # This ConfigMap doesn't exist - causing CrashLoopBackOff

