apiVersion: v1
kind: Service
metadata:
  name: broken-service
  namespace: default
spec:
  selector:
    app: web-app
    version: v1  # Service expects version=v1
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        version: v2  # Pods have version=v2 - mismatch with service selector!
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80

