apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hungry-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hungry
  template:
    metadata:
      labels:
        app: memory-hungry
    spec:
      containers:
      - name: app
        image: nginx:latest
        resources:
          requests:
            memory: "128Mi"  # Fixed: Reduced from 2Gi to 128Mi
            cpu: "100m"     # Fixed: Reduced from 500m to 100m
          limits:
            memory: "256Mi"  # Fixed: Reduced from 4Gi to 256Mi
            cpu: "200m"      # Fixed: Reduced from 1000m to 200m

