apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        version: v1  # Fixed: Changed from v2 to v1 to match service selector
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80

