apiVersion: v1
kind: ResourceQuota
metadata:
  name: hpa-quota
  namespace: default
spec:
  hard:
    pods: "1"  # This limits pods to 1, blocking HPA from scaling to 3
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"

