apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: example-mcp-server
  namespace: kagent
spec:
  deployment:
    image: ghcr.io/example/mcp-server:latest
    port: 3000
    cmd: "python"
    args: ["src/main.py"]
    env:
      - name: API_KEY
        value: "your-api-key-here"
      - name: LOG_LEVEL
        value: "info"
  transportType: "stdio"

